language: python
python:
  - "2.7"
before_install:
  - git clone https://github.com/aleaxit/gmpy.git
  - cd gmpy
  - python setup.py install
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - python setup.py install
  - python run.py trial python
